plugins:
  easecheck_enabled:
    default: false
    client: true
  easecheck_provider:
    default: "HuaweiCloud"
    client: true
  easecheck_huaweicloud_auth_token_endpoint:
    default: ""
    client: true
  easecheck_huaweicloud_text_check_endpoint:
    default: ""
    client: true
  easecheck_huaweicloud_image_check_endpoint:
    default: ""
    client: true
  easecheck_huaweicloud_project_id:
    default: ""
    client: true
  easecheck_huaweicloud_project_name:
    default: ""
    client: true
  easecheck_huaweicloud_text_check_categories:
    default: "porn,abuse,contraband,flood,ad,politics"
    client: true
  easecheck_huaweicloud_image_check_categories:
    default: "terrorism,porn,ad,politics"
    client: true
  easecheck_huaweicloud_token_validity_period:
    type: integer
    default: 12
    max: 240
    client: true
  easecheck_debug_info:
    default: false
    client: true
